### ISSUE TITLE
Number of installs

### ISSUE THREAD

**Issue by Waotest** [konovalov-maksim/play_market_parser#1]
The exact number of installs in no longer shown along with other data that used to work.
![bExMPzq](https://user-images.githubusercontent.com/7605968/94988110-3e4ff880-056b-11eb-85e0-5bdd1f727155.png)

**Comment by konovalov-maksim** [comment]
This issue is fixed in new release - https://github.com/konovalov-maksim/play_market_parser/releases/tag/1.2
