### ISSUE TITLE
The parser makes a selection of the results with a limit of 50 values per keyword. Парсер делает подборку из результатов с ограничением в 50 значений на ключевое слово.

### ISSUE THREAD

**Issue by gennadiyakulov** [konovalov-maksim/play_market_parser#3]
If we enter, for example, 6 keywords, then the parser selects only 50 applications for each keyword (a total of 300 applications), but I actually have a lot more of them. (I'm talking about the "App Search" mode). If this restriction could be removed somehow, or if the number of applications found per keyword could be increased to 500 or 1000, the program would be excellent. I also wanted to ask if there are plans to develop an analog for App Store parsing?

Если мы вводим, например, 6 ключевых слов, то парсер подбирает только по 50 приложений для каждого ключевого слова (итого 300 приложений), хо я фактически их намного больше. (я говорю про режим "Поиск приложений"). Если это ограничение можно было бы как-то убрать, либо увеличить количество найденных приложений на одно ключевое слово до 500 или 1000, программа стала бы отличной. Также хотел спросить, планируется ли разработка аналога для парсинга App Store?

**Comment by konovalov-maksim** [comment]
Google Play returns no more than 50 apps per query in page HTML. The remaining apps are loaded lazily using JS when you scroll the page. The max number of apps per query is about 250-300. Yes, this apps can also be scraped using additional http-queries, this feature can be added in future releases.

App store has only fairly simplified web version without global search. But maybe some app store scraper will be implemented in the future.
