### ISSUE TITLE
Неверный формат данных при экспорте/копировании

### ISSUE THREAD

**Issue by morethanhater** [konovalov-maksim/play_market_parser#4]
При экспорте данных результата парсинга страниц приложений, столбец "Версия", с долей вероятности, вместо реального значения содержит какую-то дату. Смена формата ячейки не помогает, т.к. значение уже изначально было залито как дата.
Если попытаться скопировать (ctrl+c) значение ячейки с ПО - результат либо такой же (для столбца "Версия"), либо еще хуже (другие столбцы тоже некорректно копируются)
Пример некорректной выгрузки во вложении.
[Приложения Google Play 23-06-2021.zip](https://github.com/konovalov-maksim/play_market_parser/files/6701439/Google.Play.23-06-2021.zip)

**Comment by konovalov-maksim** [comment]
Отображение дат вместо версий - это не проблема CSV файла, это проблема того, как Excel читает CSV файл. Если в ячейке лежат числа, разделенные точкой, и их формат напоминает дату, то Excel преобразует значение ячейки в дату. Чтобы этого не происходило, для открытия CSV файла в Excel можно создать новый файл, затем выбрать **Данные** -> **Из текстового/CSV файла**, затем выбрать CSV файл. Также для открытия CSV удобно использовать LibreOffice.

В целом эта проблема - повод добавить функцию экспорта в .xlsx, возможно она появится в новых версиях.
