### ISSUE TITLE
Number of installs (again)

### ISSUE THREAD

**Issue by Jiharb** [konovalov-maksim/play_market_parser#6]
The exact number of installs again in no longer shown along with other data that used to work.
![scraper](https://user-images.githubusercontent.com/21320939/140148907-3c72b7cf-800f-42e8-b2fb-761f7a6058dd.png)
.

**Comment by konovalov-maksim** [comment]
This issue occurs because of updates in app page source code on Google Play. It fixed in the [latest release](https://github.com/konovalov-maksim/play_market_parser/releases/tag/1.3.2)

**Comment by Jiharb** [comment]
Thanks a lot!
